apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-postgres.yaml
  - 03-configmap.yaml
  - 04-dragonfly.yaml
  - 05-n8n-main.yaml
  - 06-ingress.yaml
  - 07-n8n-worker.yaml
  - 08-resourcequota-limited.yaml
  - 09-hpa.yaml
  - 10-pdb.yaml
#  - 11-stress-job.yaml
#  - 12-backup-cronjob.yaml

